sms:
  # 标注从yml读取配置
  config-type: yaml
  # 账户上限
  account-max: 1
  blends:
    # 阿里短信例子
    ali:
      #厂商标识，标定此配置是哪个厂商，详细请看厂商标识介绍部分
      supplier: alibaba
      #您的accessKey
      access-key-id: 您的accessKey
      #您的accessKeySecret
      access-key-secret: 您的accessKeySecret
      #您的短信签名
      signature: 测试签名
      #模板ID 非必须配置，如果使用sendMessage的快速发送需此配置
      template-id: SMS_272470496
      # 模版名称
      templateName: code
    # 腾讯短信例子
    tx:
      #厂商标识
      supplier: tencent
      #您的accessKey
      access-key-id: 您的accessKey
      #您的accessKeySecret
      access-key-secret: 您的accessKeySecret
      #您的短信签名
      signature: 测试签名
      #模板ID
      template-id: 1603670
      #您的sdkAppId
      sdk-app-id: 1400761645
    # 华为短信例子
    hw:
      #厂商标识
      supplier: huawei
      #您的accessKey
      access-key-id: 您的accessKey
      #您的accessKeySecret
      access-key-secret: 您的accessKeySecret
      #您的短信签名
      signature: 测试签名
      #模板ID
      template-id: ac4888205c274b2a8263479b954c1ab5
      # APP接入地址
      url: https://smsapi.cn-north-4.myhuaweicloud.com:443
      # 模版名称
      templateName: code
      # 通道号
      sender: 8823040504797
    # 合一短信例子
    uni:
      #厂商标识
      supplier: unisms
      #您的accessKey
      access-key-id: 您的accessKey
      #您的短信签名
      signature: 测试签名
      #模板ID
      template-id: pub_verif_short
      # 模版名称
      templateName: code
      # 渠道上限
      maximum: 2
    lianlu:
      supplier: lianlu
      templateId: 模板id
      appId: 100116
      appKey: d42d7
      mchId: 100
      signName: 【test】
    cloopen:
      # 短信厂商
      supplier: cloopen
      base-url: https://app.cloopen.com:8883/2013-12-26
      access-key-id: 你的Access Key
      access-key-secret: 你的Access Key Secret
      sdkAppId: 你的应用ID
    #自定义广州掌骏短信，添加factory全路径。config,factory,SmsImpl复制其他默认实现即可，修改对应的supplier和发送核心逻辑即可
#    zhangjun:
#      supplier: zhangjun
#      factory: org.dromara.sms4j.example.zhangjun.ZhangJunFactory
#      templateId: d2a****777
#      appId: 64c52d2a****77775fe72e3
#      sid: d2a****777
#      url: https://sms.idowe.com/**/**/**/send
    qiniu:
      access-key-id: z_fGcmAj0XOlM_K0KhurGbesdh1ec_nJNCjmo8Ag
      access-key-secret: xz1AzgPsVnhQaPHy1y_tvajgn3fIVL5bw_qy_hLK
      templateId: 1752130467315859456
      signatureId: 1751851165571624960
      templateName: code
sms-oa:
  config-type: yaml
  oas:
    oaDingTalkByYaml: # configId
      isEnable: true # 表示该配置是否生效(默认生效,false表示不生效)
      supplier: dingding # 厂商标识
      tokenId: 您的accessKey
      sign: 您的sign
    oaByteTalkByYaml: # configId
      supplier: feishu # 厂商标识
      tokenId: 您的accessKey
      sign: 您的sign
    oaWeTalkByYaml:
      supplier: wetalk # 厂商标识
      tokenId: 您的sign
  core-pool-size: 20
  queue-capacity: 20
  max-pool-size: 20