sms:
  # 标注从yml读取配置
  config-type: yaml
  blends:
    # 阿里短信例子
    ali:
      #厂商标识，标定此配置是哪个厂商，详细请看厂商标识介绍部分
      supplier: alibaba
      #您的accessKey
      access-key-id: 您的accessKey
      #您的accessKeySecret
      access-key-secret: 您的accessKeySecret
      #您的短信签名
      signature: 测试签名
      #模板ID 非必须配置，如果使用sendMessage的快速发送需此配置
      template-id: SMS_272470496
      # 模版名称
      templateName: code
    # 腾讯短信例子
    tx:
      #厂商标识
      supplier: tencent
      #您的accessKey
      access-key-id: 您的accessKey
      #您的accessKeySecret
      access-key-secret: 您的accessKeySecret
      #您的短信签名
      signature: 测试签名
      #模板ID
      template-id: 1603670
      #您的sdkAppId
      sdk-app-id: 1400761645
    # 华为短信例子
    hw:
      #厂商标识
      supplier: huawei
      #您的accessKey
      access-key-id: 您的accessKey
      #您的accessKeySecret
      access-key-secret: 您的accessKeySecret
      #您的短信签名
      signature: 测试签名
      #模板ID
      template-id: ac4888205c274b2a8263479b954c1ab5
      # APP接入地址
      url: https://smsapi.cn-north-4.myhuaweicloud.com:443
      # 模版名称
      templateName: code
      # 通道号
      sender: 8823040504797
    # 合一短信例子
    uni:
      #厂商标识
      supplier: unisms
      #您的accessKey
      access-key-id: 您的accessKey
      #您的短信签名
      signature: 测试签名
      #模板ID
      template-id: pub_verif_short
      # 模版名称
      templateName: code
    lianlu:
      supplier: lianlu
      templateId: 模板id
      appId: 100116
      appKey: d42d7
      mchId: 100
      signName: 【test】
    cloopen:
      # 短信厂商
      supplier: cloopen
      base-url: https://app.cloopen.com:8883/2013-12-26
      access-key-id: 你的Access Key
      access-key-secret: 你的Access Key Secret
      sdk-app-id: 你的应用ID